Website_clothe/Website_clothe/Areas/Admin/Controllers/DetailCatagoryController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Runtime;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Website_clothe.Models;

namespace Website_clothe.Areas.Admin.Controllers
{
    
    public class DetailCatagoryController : Controller
    {
        public Server_clothesEntities5 db = new Server_clothesEntities5();
        // GET: Admin/DetailCatagory
        [HttpGet]
        public ActionResult Index( )
        {
            if (Session["AdminUsername"] == null)
            {
                return View("/Areas/Admin/Views/AdminUser/Login.cshtml");
            }
            List<Danhmucsanpham> kq = db.Danhmucsanphams.OrderBy(c => c.Madanhmuc).ToList();
            List<Chitietdanhmuc> query = null;
            var categoryIds = kq.Select(c => c.Madanhmuc).ToList();
            query = db.Chitietdanhmucs.Where(p => p.Madanhmuc == categoryIds.FirstOrDefault()).ToList();
            
            

            ViewBag.kq = kq;
           
             return View(query);
        }
        public JsonResult loadtable(int id)
        {
            string json = "";
            var result = db.Chitietdanhmucs.Where(c => c.Madanhmuc == id).ToList();
            if(result.Count > 0)
            {
                List<datajson> data = new List<datajson>();
                result.ForEach(c =>
                {
                    var kq1 = new datajson
                    {
                        mactdm = c.ID_Chitietdanhmuc,
                        hinhanh = c.HinhAnh,
                        tenctdm = c.Tenchitietdanhmuc,
                        madmg = (int)c.Madanhmuc,

                    };
                    data.Add(kq1);
                });
                json = JsonConvert.SerializeObject(data);
            }
            return Json(json, JsonRequestBehavior.AllowGet);
        }
        public async Task<ActionResult> Delete(int id_ctdm)
        {
            var CtDanhmuc = db.Chitietdanhmucs.FirstOrDefault(x => x.ID_Chitietdanhmuc == id_ctdm);
            if (CtDanhmuc != null)
            {
                var sanpham = db.Sanphams.Where(x => x.Chitietdanhmuc == CtDanhmuc.ID_Chitietdanhmuc).ToList();
                if (sanpham.Any())
                {
                    var sanphamIDs = sanpham.Select(x => x.Masanpham).ToList();
                    var btsanpham = db.Bienthesanphams.Where(x => sanphamIDs.Contains((int)x.ID_Sanpham)).ToList();
                    if (btsanpham.Any())
                    {
                        var btsanphamIDs = btsanpham.Select(x => x.ID_Bienthesanpham).ToList();
                        var donmuact = db.Chitietdonhangs.Where(x => btsanphamIDs.Contains((int)x.ID_Sanphambienthe)).ToList();
                        if (donmuact.Any())
                        {
                            var donDatIDs = donmuact.Where(x => x.ID_Donhang.HasValue).Select(x => x.ID_Donhang.Value).ToList();
                            var dondat = db.Donmuahangs.Where(x => donDatIDs.Contains(x.ID_Donhang)).ToList();
                            db.Chitietdonhangs.RemoveRange(donmuact);
                            await db.SaveChangesAsync();
                            if (dondat.Any())
                            {
                                db.Donmuahangs.RemoveRange(dondat);
                               await db.SaveChangesAsync();
                            }
                            
                        }
                        var phieunhapct = db.Chitietphieunhaps.Where(x => btsanphamIDs.Contains((int)x.ID_Bienthesanpham)).ToList();
                        if (phieunhapct.Any())
                        {
                            var phieunhapIDs = phieunhapct.Where(x => x.ID_Phieunhaphang.HasValue).Select(x => x.ID_Phieunhaphang.Value).ToList();
                            var phieunhap = db.Phieunhaps.Where(x => phieunhapIDs.Contains(x.ID_Phieunhap)).ToList();
                            db.Chitietphieunhaps.RemoveRange(phieunhapct);
                            await db.SaveChangesAsync();
                            if (phieunhap.Any())
                            {
                                db.Phieunhaps.RemoveRange(phieunhap);
                                await db.SaveChangesAsync();
                            }
                        }
                        db.Bienthesanphams.RemoveRange(btsanpham);
                      await  db.SaveChangesAsync();
                    }
                    var hinhsp = db.HinhanhSanphams.Where(x => sanphamIDs.Contains((int)x.Masanpham)).ToList();
                    if (hinhsp.Any())
                    {
                        db.HinhanhSanphams.RemoveRange(hinhsp);
                      await  db.SaveChangesAsync();
                    }
                    db.Sanphams.RemoveRange(sanpham); 
                   await  db.SaveChangesAsync();
                }
                db.Chitietdanhmucs.Remove(CtDanhmuc);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Create()
        {
            if (Session["AdminUsername"] == null)
            {
                return View("/Areas/Admin/Views/AdminUser/Login.cshtml");
            }
            var result = db.Danhmucsanphams.ToList();
            return View(result);
        }
        [HttpPost]
        public ActionResult Create(int danhmucsp,string name_detaildb, HttpPostedFileBase image)
        {
            var result = db.Danhmucsanphams.ToList();
            var query = db.Chitietdanhmucs.Where(x => x.Tenchitietdanhmuc == name_detaildb);
            if(query.Any())
            {
                ViewBag.error = "Tên chi tiết danh mục đã tồn tại trên hệ thống";
                return View(result);
            }
            if(image == null)
            {
                ViewBag.error = "bạn chưa chọn ảnh";
                return View(result);
            }
            else
            {
                if (!IsImageFile(image))
                {
                    ViewBag.error = "File bạn chọn không phải là file ảnh";
                    return View(result);
                }
                try
                {
                    string filename = Path.GetFileName(image.FileName);
                    string extension = Path.GetExtension(filename);
                    string uniqueFileName = Path.GetFileNameWithoutExtension(filename) + "_" + Guid.NewGuid().ToString() + extension;
                    string path = Path.Combine(Server.MapPath("~/Content/img"), uniqueFileName);
                    image.SaveAs(path);

                    //lưu dữ liệu xuống database
                    var kq = new Chitietdanhmuc
                    {
                        Madanhmuc = danhmucsp,
                        Tenchitietdanhmuc = name_detaildb,
                        HinhAnh = uniqueFileName
                    };
                    db.Chitietdanhmucs.Add(kq);
                    db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ViewBag.Message = "Lỗi khi upload ảnh: " + ex.Message;
                    return View(result);
                }
            }
        }
        [HttpGet]
        public ActionResult Edit(int id_ctdm)
        {
            var result = db.Chitietdanhmucs.Where(c => c.ID_Chitietdanhmuc == id_ctdm).FirstOrDefault();
            ViewBag.danhmucsp = db.Danhmucsanphams.ToList();
            return View(result);
        }
        [HttpPost]
        public ActionResult Edit(int danhmucsp,string tenctdanhmuc,int mactdm, HttpPostedFileBase image)
        {
            ViewBag.danhmucsp = db.Danhmucsanphams.ToList();
            var result = db.Chitietdanhmucs.Where(c => c.ID_Chitietdanhmuc == mactdm).FirstOrDefault();
            
            
            
            if (image != null)
            {
                
                if(IsImageFile(image))
                {
                    string filename = Path.GetFileName(image.FileName);
                    string extension = Path.GetExtension(filename);
                    string uniqueFileName = Path.GetFileNameWithoutExtension(filename) + "_" + Guid.NewGuid().ToString() + extension;
                    string path = Path.Combine(Server.MapPath("~/Content/img"), uniqueFileName);
                    image.SaveAs(path);

                    var query = db.Chitietdanhmucs.First(c => c.ID_Chitietdanhmuc == mactdm);
                    query.Madanhmuc = danhmucsp;
                    query.Tenchitietdanhmuc = tenctdanhmuc;
                    query.HinhAnh = uniqueFileName;
                    UpdateModel(query);
                    db.SaveChangesAsync();
                }
                else
                {
                    ViewBag.error = "Bạn vừa chọn không phải là file ảnh";
                    return View(result);
                }
            }
            else
            {
                var query = db.Chitietdanhmucs.First(c => c.ID_Chitietdanhmuc == mactdm);
                query.Madanhmuc = danhmucsp;
                query.Tenchitietdanhmuc = tenctdanhmuc;
                UpdateModel(query);
                db.SaveChangesAsync();
            }
            return RedirectToAction("Index");
        }

        private bool IsImageFile(HttpPostedFileBase file)
        {
            if (file != null)
            {
                // Kiểm tra loại MIME của file để xác định xem nó có phải là file ảnh hay không
                string[] allowedImageTypes = { "image/jpeg", "image/jpg", "image/png", "image/gif" };
                return allowedImageTypes.Contains(file.ContentType);
            }

            return false;
        }

    }
    public class datajson
    {
        public int mactdm;
        public string tenctdm;

Website_clothe/Website_clothe/Areas/Admin/Views/DetailCatagory/Create.cshtml
@{
    ViewBag.Title = "Add";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@model IEnumerable<Website_clothe.Models.Danhmucsanpham>
<div class="container-fluid mt-4 px-4">

    <div class="card">
        <div class="card-header d-flex justify-content-between">
            <h3>
                Thêm mới chi tiết danh mục
            </h3>
            <button class="btn btn-info " onclick="location.href= ' @Url.Action("Index", "DetailCatagory") ' ">
                <div class="text-white">Quay lại</div>
            </button>
        </div>
        <div class="card-body">
            <form asp-controller="Category" asp-action="Add" method="post" enctype="multipart/form-data">
                <p style="color:red">
                    @ViewBag.error
                </p>
                <div class="mb-3">
                    <label class="form-label">Tên danh mục</label>
                    <select name="danhmucsp" class="form-select" required>
                        <option value="">Chọn danh mục sản phẩm</option>
                        @foreach(var item in Model)
                        {
                            <option value="@item.Madanhmuc">@item.Tendanhmuc</option>
                        }
                    </select>
                </div>
                <div class="mb-3">
                    <label class="form-label">Tên chi tiết danh mục</label>
                    <input type="text" class="form-control" name="name_detaildb" required/>
                </div>
                <div class="mb-3">
                        <label class="form-label">Hình ảnh</label>
                        <input type="file" class="form-control" name="image" onchange="previewImage(this);">
                </div>
                <div class="mb-3">
                    <img id="imagePreview" class="d-block img-thumbnail" width="200" height="200" alt="" style=" background-color: rgb(235, 235, 235);color: white">
                </div>
                
                <input type="submit" class="btn btn-success" value="Submit" />
            </form>
        </div>
    </div>
</div>
<script>
        function previewImage(input) {
            var imagePreview = document.getElementById("imagePreview");
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    imagePreview.src = e.target.result;
                };
                reader.readAsDataURL(input.files[0]);
            } else {
                imagePreview.src = "path-to-empty-image.jpg";
            }
        }
</script>

Website_clothe/Website_clothe/Areas/Admin/Views/DetailCatagory/Edit.cshtml
@model Website_clothe.Models.Chitietdanhmuc
@{
    var result = ViewBag.danhmucsp;
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<h2>Edit</h2>
<div class="container-fluid mt-4 px-4">
    <div class="card">
        <div class="card-header d-flex justify-content-between">
            <h4>Chỉnh sửa danh mục</h4>
            <button class="btn btn-info " onclick="location.href= ' @Url.Action("Index", "DetailCatagory") ' ">
                <div class="text-white">Quay lại</div>
            </button>
        </div>
        <div class="card-body">
            <form asp-controller="Category" asp-action="Edit" method="post" enctype="multipart/form-data">
                <p style="color:red">
                    @ViewBag.error
                </p>
                <div class="mb-3">
                    <label class="form-label">Tên danh mục</label>
                    <input type="text" class="form-control" placeholder="Nhập tên danh mục" value="@Model.Tenchitietdanhmuc" name="tenctdanhmuc" required/>
                </div>
                <div class="mb-3">
                    <label class="form-label">Tên danh mục</label>
                    <select name="danhmucsp" class="form-select" required>
                        <option value="">Chọn danh mục sản phẩm</option>
                        @foreach (var item in result)
                        {
                            if (item.Madanhmuc == Model.Madanhmuc)
                            {
                                <option value="@item.Madanhmuc" selected>@item.Tendanhmuc</option>
                            }
                            else
                            {
                                <option value="@item.Madanhmuc">@item.Tendanhmuc</option>
                            }
                        }
                    </select>
                </div>
                <div class="mb-3">
                    <label class="form-label">Hình ảnh</label>
                    <input type="file" class="form-control" name="image" onchange="previewImage(this);">
                </div>
                <div class="mb-3">
                    <img id="imagePreview" class="d-block img-thumbnail" src="~/Content/img/@Model.HinhAnh"  alt="" style=" background-color: rgb(235, 235, 235);color: white;width:200px;height:200px" >
                </div>
                <input type="hidden" value="@Model.ID_Chitietdanhmuc" name="mactdm"/>
                <input type="submit" class="btn btn-success" value="Submit" />
            </form>
        </div>
    </div>
</div>
<script>
    function previewImage(input) {
        var imagePreview = document.getElementById("imagePreview");
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                imagePreview.src = e.target.result;
            };
            reader.readAsDataURL(input.files[0]);
        } else {
            imagePreview.src = "path-to-empty-image.jpg";
        }
    }
</script>

Website_clothe/Website_clothe/Areas/Admin/Views/DetailCatagory/Index.cshtml
@model List<Website_clothe.Models.Chitietdanhmuc>
@{
    ViewBag.Title = "Chi tiết danh mục";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var kq = ViewBag.kq;
}

<div class="container-fluid mt-4 px-4">
    <div class="card">
        <div class="card-header d-flex justify-content-between">
            <h3>
                Chi tiêt danh mục
            </h3>
            <button class="btn btn-primary " onclick="location.href= ' @Url.Action("Create", "DetailCatagory") ' ">
                <div class="text-white">Thêm mới</div>
            </button>
        </div>
        <div class="card-body">

            <div class="mb-3">
                <select id="categorySelect" class="form-select" aria-label="Default select example">
                    @if (kq.Count == 0)
                    {
                        <option value="" selected>Không có dữ liệu</option>
                    }
                    else
                    {
                        foreach (var item in kq)
                        {
                            <option value="@item.Madanhmuc">@item.Tendanhmuc</option>
                        }
                    }

                </select>
            </div>

            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>STT</th>
                        <th>Hình ảnh</th>
                        <th>Tên</th>
                        <th>Hành động</th>
                    </tr>
                </thead>
                <tbody >
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.ID_Chitietdanhmuc</td>
                            <td><img src="~/Content/img/@item.HinhAnh" class="img-fluid img-thumbnail" style="width:100px;height:100px;" /></td>
                            <td>@item.Tenchitietdanhmuc</td>
                            <td>
                                <a class="btn btn-warning" href="@Url.Action("Edit","DetailCatagory",
                            new {id_ctdm = item.ID_Chitietdanhmuc})">Sửa</a>
                                <a class="btn btn-danger" href="@Url.Action("Delete", "DetailCatagory", new { id_ctdm = item.ID_Chitietdanhmuc })">Xóa</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {


        // Gắn sự kiện change cho thẻ select
        $("#categorySelect").change(function () {
            // Lấy giá trị đã chọn từ thẻ select
            $(".table-hover tbody").html("")
            var selectedOption = $(this).val();

            // Gửi yêu cầu AJAX đến controller
            $.ajax({
                type: "GET",
                url: "/Admin/DetailCatagory/loadtable",
                data: { id: selectedOption },
                success: function (data) {
                    // Cập nhật dữ liệu trong bảng dựa trên dữ liệu nhận được từ controller

                    let html = ""

                    if (data.trim() == "") {
                        html = "<tr><td>không có dữ liệu tìm thấy</td><td></td><td></td></tr>"
                    } else {
                        let obj = JSON.parse(data)
                        for (i = 0; i < obj.length; i++) {
                            html += `
                        <tr><td>${obj[i].mactdm}</td>
                            <td><img src="/Content/img/${obj[i].hinhanh}" class="img-fluid img-thumbnail" style="width:100px;height:100px;" />
                           </td>
                        <td>${obj[i].tenctdm}</td>
                        <td>
                            <a class="btn btn-warning" href="/Admin/DetailCatagory/Edit?id_ctdm=${obj[i].mactdm}">Sửa</a>
                            <a class="btn btn-danger" href="/Admin/DetailCatagory/Delete?id_ctdm=${obj[i].mactdm}">Xóa</a>
                        </td>
                        </tr>`
                        }
                    }

                    $(".table-hover tbody").html(html);
                },
                
            });
        });
    });

</script>