Website_clothe/Website_clothe/Areas/Admin/Controllers/ConditionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Website_clothe.Models;

namespace Website_clothe.Areas.Admin.Controllers
{
    public class ConditionController : Controller
    {
        Server_clothesEntities5 db = new Server_clothesEntities5();
        public ActionResult Index()
        {
            if (Session["AdminUsername"] == null)
            {
                return View("/Areas/Admin/Views/AdminUser/Login.cshtml");
            }
            var model = db.TrangThaiDHs.ToList();
            return View(model);
        }
        [HttpGet]
        public ActionResult Create()
        {
            if (Session["AdminUsername"] == null)
            {
                return View("/Areas/Admin/Views/AdminUser/Login.cshtml");
            }
            return View();
        }
        [HttpPost]
        public ActionResult Create(string tentrangthai)
        {
            
                var query = db.TrangThaiDHs.Where(x => x.TenTrangThai == tentrangthai);
            if (query.Any())
            {
                ViewBag.error = "Trạng thái đã có trên hệ thống";
                return View();
            }
                var data = new TrangThaiDH
                {
                    TenTrangThai = tentrangthai,
                };
                db.TrangThaiDHs.Add(data);
                db.SaveChanges();
                return RedirectToAction("Index");
            
           
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var model = db.TrangThaiDHs.FirstOrDefault(x => x.ID_TrangThai == id);
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(int id,string tentrangthai)
        {
            
           
                var data = db.TrangThaiDHs.FirstOrDefault(x => x.ID_TrangThai == id);
                data.TenTrangThai = tentrangthai;
                UpdateModel(data);
                db.SaveChanges();
                return RedirectToAction("Index");
            
         
        }
        public ActionResult Delete (int id)
        {
            var data = db.TrangThaiDHs.FirstOrDefault(x => x.ID_TrangThai == id);
            var donmuahang = db.Donmuahangs.Where(x => x.ID_Trangthai == id).ToList();
            List<int> madon = donmuahang.Select(x=> x.ID_Donhang).ToList();
            var chitietdon = db.Chitietdonhangs.Where(x => madon.Contains((int)x.ID_Donhang)).ToList();
            db.TrangThaiDHs.Remove(data);
            db.SaveChanges();

            if(donmuahang.Count() > 0)
            {
                db.Donmuahangs.RemoveRange(donmuahang);
                db.SaveChanges();
            }
            if(chitietdon.Count() > 0)
            {
                db.Chitietdonhangs.RemoveRange(chitietdon); 
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

Website_clothe/Website_clothe/Areas/Admin/Views/Condition/Create.cshtml
@{
    ViewBag.Title = "Add-category";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<div class="container-fluid mt-4 px-4">

    <div class="card">
        <div class="card-header d-flex justify-content-between">
            <h4>Thêm mới trạng thái</h4>
            <button class="btn btn-info " onclick="location.href='@Url.Action("Index", "Condition")'">
                <div class="text-white">Quay lại</div>
            </button>
        </div>
        <div class="card-body">
            <form asp-controller="Condition" asp-action="Create" method="post">
                <p style="color:red">
                    @ViewBag.error
                </p>
                <div class="mb-3">
                    <label class="form-label">Tên trạng thái</label>
                    <input type="text" class="form-control" placeholder="Nhập tên trạng thái" value="" name="tentrangthai" required />
                </div>
                <input type="submit" class="btn btn-success" value="Submit" />
            </form>
        </div>
    </div>
</div>

Website_clothe/Website_clothe/Areas/Admin/Views/Condition/Edit.cshtml
@model Website_clothe.Models.TrangThaiDH

@{
    ViewBag.Title = "Edit-Condition";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid mt-4 px-4">

    <div class="card">
        <div class="card-header d-flex justify-content-between">
            <h4>Chỉnh sửa trạng thái</h4>
            <button class="btn btn-info " onclick="location.href='@Url.Action("Index", "Condition")'">
                <div class="text-white">Quay lại</div>
            </button>
        </div>
        <div class="card-body">
            <form asp-controller="Condition" asp-action="Edit" method="post">
                
                <div class="mb-3">
                    <label class="form-label">Tên trạng thái</label>
                    <input type="text" class="form-control" placeholder="Nhập tên trạng thái" value="@Model.TenTrangThai" name="tentrangthai" required />
                </div>
                <input type="hidden" value="@Model.ID_TrangThai" name="id" />

                <input type="submit" class="btn btn-success" value="Submit" />

            </form>
        </div>
    </div>
</div>

Website_clothe/Website_clothe/Areas/Admin/Views/Condition/Index.cshtml
@model List<Website_clothe.Models.TrangThaiDH>

@{
    ViewBag.Title = "Quản lý trạng thái đơn hàng";
}
<div class="container-fluid mt-4 px-4">
    <div class="card">
        <div class="card-header d-flex justify-content-between">
            <h3>Danh sách trạng thái</h3>
            <button class="btn btn-primary " onclick="location.href= ' @Url.Action("Create", "Condition") ' ">
                <div class="text-white">Thêm mới</div>
            </button>
        </div>
        <div class="card-body">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>STT</th>
                        <th>Tên trạng thái</th>
                        <th>Hành động</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.ID_TrangThai</td>
                          
                            <td>@item.TenTrangThai</td>
                            <td>
                                @Html.ActionLink("Sửa", "Edit", new { id = item.ID_TrangThai }, new { @class = "btn btn-warning" })

                                <a class="btn btn-danger" href="@Url.Action("Delete", "Condition", new { id = item.ID_TrangThai })">Xóa</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>