Website_clothe/Website_clothe/Areas/Admin/Controllers/BuyBillController.cs
using SelectPdf;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Website_clothe.Models;

namespace Website_clothe.Areas.Admin.Controllers
{
    public class BuyBillController : BaseController
    {
        Server_clothesEntities5 db = new Server_clothesEntities5();
        public ActionResult Index()
        {
            if (Session["AdminUsername"] == null)
            {
                return View("/Areas/Admin/Views/AdminUser/Login.cshtml");
            }
            var model = db.Donmuahangs.ToList();
            return View(model);
        }
        public ActionResult Detail(int id)
        {
                var data = db.Chitietdonhangs.Where(x => x.ID_Donhang == id).ToList();
                var model = db.Donmuahangs.FirstOrDefault(x => x.ID_Donhang == id);
            
            

                //lấy ra các biến thể sản phẩm mà mã của nó nằm trong chi tiết đơn hàng

                var idSanPhamBienthe = data.Select(ct => ct.ID_Sanphambienthe).ToList();
                var item2 = db.Bienthesanphams.Where(x => idSanPhamBienthe.Contains(x.ID_Bienthesanpham)).ToList();

                //lấy ra size mà mã nằm trong biến thể

                var idSizebienthe = item2.Select(bt => bt.SizeID).ToList();
                var item3 = db.Sizes.Where(x => idSizebienthe.Contains(x.ID_Size)).ToList();

                //lấy ra màu mà mã nằm trong biến thể

                var idMaubienthe = item2.Select(bt => bt.ID_Mau).ToList();
                var item4 = db.MauSacs.Where(x => idMaubienthe.Contains(x.ID_Mau)).ToList();

                //lấy ra các sản phẩm nằm trong biến thể sản phẩm
                var idsanphambienthe = item2.Select(bt => bt.ID_Sanpham).ToList();
                var item5 = db.Sanphams.Where(x => idsanphambienthe.Contains(x.Masanpham)).ToList();
                List<detailshoppingbill> bill = new List<detailshoppingbill>();
                int tongdon = 0;
                foreach (var i_tem in data)
                {
                    detailshoppingbill query = new detailshoppingbill
                    {
                        madonhang = (int)i_tem.ID_Donhang,
                        masanpham = (int)i_tem.ID_Sanphambienthe,
                        soluong = i_tem.Soluong,
                    };
                    int sizeid = 0, colorid = 0, sanphamid = 0;
                    foreach (var i_tem2 in item2)
                    {
                        if (i_tem2.ID_Bienthesanpham == i_tem.ID_Sanphambienthe)
                        {
                            sizeid = (int)i_tem2.SizeID;
                            colorid = (int)i_tem2.ID_Mau;
                            sanphamid = (int)i_tem2.ID_Sanpham;

                            break;
                        }
                    }
                    foreach (var i_tem3 in item3)
                    {
                        if (i_tem3.ID_Size == sizeid)
                        {
                            query.size = i_tem3.TenSize;
                            break;
                        }
                    }
                    foreach (var i_tem4 in item4)
                    {
                        if (i_tem4.ID_Mau == colorid)
                        {
                            query.mausac = i_tem4.Tenmau; break;
                        }
                    }
                    foreach (var i_tem5 in item5)
                    {
                        if (i_tem5.Masanpham == sanphamid)
                        {
                            query.tensanpham = i_tem5.Tensanpham;
                            query.dongia = (int)i_tem5.Giaban;
                            query.thanhtien = query.dongia * query.soluong;
                            tongdon += query.thanhtien;
                            break;

                        }
                    }
                    bill.Add(query);
                }
            
            ViewBag.Nguoimua = db.Nguoidungs.Where(x => x.ID_Nguoidung == model.ID_Nguoidung).FirstOrDefault();
            ViewBag.Trangthai = db.TrangThaiDHs.ToList();
            ViewBag.Bill = bill;
            ViewBag.tongdon = tongdon;
            return View(model);
        }
        [HttpPost]
        public ActionResult Changeofstatusbill(int id, int valueofbill)
        {
            var data = db.Donmuahangs.FirstOrDefault(x => x.ID_Donhang == id);
            var query = db.Chitietdonhangs.Where(x => x.ID_Donhang == id);
            if (valueofbill == 2002)
            {
                
                if (query.Any())
                {
                    List<int?> listNullableInts = query.Select(x => x.ID_Sanphambienthe).ToList();
                    List<int> masp = listNullableInts
                            .Where(x => x.HasValue) // Lọc ra các giá trị không null
                            .Select(x => x.Value)   // Lấy giá trị không null
                            .ToList();
                    var result = db.Bienthesanphams.Where(x => masp.Contains(x.ID_Bienthesanpham)).ToList();
                    foreach(var item in result)
                    {
                        foreach(var item2 in query)
                        {
                            if(item2.ID_Sanphambienthe == item.ID_Bienthesanpham)
                            {
                                item.Soluongton -= item2.Soluong;
                                
                                
                                break;
                            }
                        }
                    }
                }
            }
            else
            {
                if (query.Any())
                {
                    List<int?> listNullableInts = query.Select(x => x.ID_Sanphambienthe).ToList();
                    List<int> masp = listNullableInts
                            .Where(x => x.HasValue) // Lọc ra các giá trị không null
                            .Select(x => x.Value)   // Lấy giá trị không null
                            .ToList();
                    var result = db.Bienthesanphams.Where(x => masp.Contains(x.ID_Bienthesanpham)).ToList();
                    foreach (var item in result)
                    {
                        foreach (var item2 in query)
                        {
                            if (item2.ID_Sanphambienthe == item.ID_Bienthesanpham)
                            {
                                item.Soluongton += item2.Soluong;
                                
                                break;
                            }
                        }
                    }
                }
            }
            data.ID_Trangthai = valueofbill;
            UpdateModel(data);
            db.SaveChanges();
            return Json(new { success = true });
        }
        
        public ActionResult DeleteBill (int id)
        {
            var data = db.Donmuahangs.FirstOrDefault(x => x.ID_Donhang == id);
            var detaildata = db.Chitietdonhangs.Where(x => x.ID_Donhang == data.ID_Donhang).ToList();
            if (detaildata != null)
            {
                db.Chitietdonhangs.RemoveRange(detaildata);
            }
            db.Donmuahangs.Remove(data);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
        public ActionResult Generatepdf(int idbill)
        {
            var order = (from x in db.Donmuahangs
                         where x.ID_Donhang == idbill
                         join y in db.Nguoidungs on x.ID_Nguoidung equals y.ID_Nguoidung
                         select new
                         {
                             madonhang = x.ID_Donhang,
                             ngaytao = x.Ngaytao,
                             Tennguoidung = x.Tennguoidung,
                             sodt = y.SoDT,
                             Diachi = x.DiaChi,
                             Tongdon = x.Tongdonhang
                         }).First();

            var detailorder = (from x in db.Chitietdonhangs
                               where x.ID_Donhang == idbill
                               join y in db.Bienthesanphams on x.ID_Sanphambienthe equals y.ID_Bienthesanpham
                               join z in db.Sanphams on y.ID_Sanpham equals z.Masanpham
                               join a in db.Sizes on y.SizeID equals a.ID_Size
                               join b in db.MauSacs on y.ID_Mau equals b.ID_Mau
                               select new
                               {
                                   mabienthe = y.ID_Bienthesanpham,
                                   masanpham = z.Masanpham,
                                   Tensanpham = z.Tensanpham,
                                   Size = a.TenSize,
                                   Mau = b.Tenmau,
                                   Soluongmua = x.Soluong,
                                   Gia = z.Giaban,
                                   Thanhtien = x.Thanhtien
                               }).ToList();

            billoforder bill = new billoforder();
            bill.madonhang = order.madonhang;
            bill.ngaydat = (DateTime)order.ngaytao;
            bill.Tennguoidung = order.Tennguoidung;
            bill.sodt = order.sodt;
            bill.Diachi = order.Diachi;
            bill.Tongdon = (int) order.Tongdon;

            foreach(var item in detailorder)
            {
                var query = new detailbillorder
                {
                    mabienthe = item.mabienthe,
                    masanpham = item.masanpham,
                    Tensanpham = item.Tensanpham,
                    Size = item.Size,
                    Mau = item.Mau,
                    Soluongmua = item.Soluongmua,
                    Gia = (int)item.Gia,
                    Thanhtien = (int)item.Thanhtien,
                };
                bill.ctdh.Add(query);
            }

Website_clothe/Website_clothe/Areas/Admin/Views/BuyBill/Detail.cshtml
@model Website_clothe.Models.Donmuahang


@{ 
    ViewBag.Title = "Chi tiết đơn hàng";
    var people = ViewBag.Nguoimua;
    var bill = ViewBag.Bill;
    var tongdon = ViewBag.tongdon;
    var trangthai = ViewBag.Trangthai;

}
<div class="container-fluid mt-4 px-4">
    <div class="card">
        <div class="card-header d-flex justify-content-between">
            <h4>Chi tiết đơn hàng</h4>
            <div class="card-tool">
                <button class="btn btn-info " onclick="location.href='@Url.Action("Index", "BuyBill")'">
                    <div class="text-white">Quay lại</div>
                </button>
                <a class="btn btn-danger prindbill" id="@Model.ID_Donhang" href="#">
                    <div class="text-white">In hóa đơn</div>
                </a>
            </div>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-12">
                    <div class="my-2 row">
                        <div class="col-3"><span class="fs-5" style="font-family:Arial">Mã đơn hàng:</span></div>
                        <div class="col-9"><span style="font-family:Arial">@Model.ID_Donhang</span></div>
                    </div>
                    <div class="my-2 row">
                        <div class="col-3"><span class="fs-5" style="font-family:Arial">Tên người mua hàng:</span></div>
                        <div class="col-9"><span style="font-family:Arial">@Model.Tennguoidung</span></div>
                    </div>
                    <div class="my-2 row">
                        <div class="col-3">
                            <span class="fs-5" style="font-family:Arial">Địa chỉ giao hàng:</span>
                        </div>
                        <div class="col-9">
                            <span style="font-family:Arial">@Model.DiaChi</span>
                        </div>
                    </div>
                    <div class="my-2 row">
                         <div class="col-3">
                             <span class="fs-5" style="font-family:Arial">Ngày đặt hàng:</span>
                         </div>
                        <div class="col-9">
                            <span style="font-family:Arial">@Model.Ngaytao.Value.ToString("dd/MM/yyyy")</span>
                        </div>
                    </div>
                    <div class="my-2 row">
                        <div class="col-3">
                            <span class="fs-5" style="font-family:Arial">Email:</span>
                        </div>
                        <div class="col-9">
                            <span style="font-family:Arial">@people.Email</span>
                        </div>
                    </div>
                    <div class="my-2 row">
                        <div class="col-3">
                            <span class="fs-5" style="font-family:Arial">Số điện thoại:</span>
                        </div>
                        <div class="col-9">
                            <span style="font-family:Arial">@people.SoDT</span>
                        </div>
                    </div>
                </div>
                <div class="col-12">
                    <div class="row">
                        <div class="col-12">
                            <h5 class="my-5">Danh sách sản phẩm mua</h5>
                        </div>
                        <div class="col-12">
                            <table class="table text-center">
                                <thead>
                                    <tr>
                                        <th>Mã sản phẩm</th>
                                        <th>Tên sản phẩm</th>
                                        <th>Size</th>
                                        <th>Màu</th>
                                        <th>Số lượng</th>
                                        <th>Đơn giá</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in bill)
                                    {
                                        <tr>
                                            <td>@item.masanpham</td>
                                            <td>@item.tensanpham</td>
                                            <td>@item.size</td>
                                            <td class="d-flex justify-content-center">
                                                <div style="border:2px solid rgb(52, 42, 42);border-radius:20px; width:30px;height:30px;background-color:@item.mausac;"></div>
                                            </td>
                                            <td>@item.soluong</td>
                                            <td>@item.dongia đ</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                        <div class="col-12">
                            <div class="row">
                                <div class="col-9">
                                    <span class="fs-5" style="font-family:Arial">Tổng đơn:</span>
                                </div>
                                <div class="col-3 d-flex justify-content-end align-items-center">
                                    <span style="font-family:Arial;margin-right:25px">@tongdon đ</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 my-3">
                            <div class="col-12 py-2">
                                <span class="fs-5" style="font-family:Arial">Trạng thái đơn hàng:</span>
                            </div>
                            <div class="col-12">
                                <select class="form-select" id="changestatus">
                                    @foreach(var item in trangthai)
                                    {
                                        if(item.ID_TrangThai == Model.ID_Trangthai)
                                        {
                                            <option value="@item.ID_TrangThai" selected disabled>@item.TenTrangThai</option>
                                        }
                                        else {
                                            <option value="@item.ID_TrangThai">@item.TenTrangThai</option>
                                        }
                                    }
                                </select>
                            </div>
                        </div>
                        <div class="col-12 my-3 d-flex justify-content-center align-items-center">
                            <button type="button" class="btn btn-success btn-submit" id="@Model.ID_Donhang">Cập nhật đơn hàng</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        
        $('body').on('click', '.btn-submit', function () {
            
            var id = this.id
            var lis = $('#changestatus').val();

            $.ajax({
                url: '/Admin/BuyBill/Changeofstatusbill',
                type: 'POST',
                data: {
                    id : id,
                    valueofbill : lis
                },
                success: function (rs) {
                    if (rs.success) {
                        alert('Trạng thái đơn hàng được cập nhật')
                        // Hủy thuộc tính disabled của tất cả các options
                        $('#changestatus option').prop('disabled', false);

                        // Lấy trạng thái mới đã cập nhật
                        var updatedStatus = lis;

                        // Tìm option tương ứng với trạng thái mới và làm cho nó selected và disabled
                        $('#changestatus option[value="' + updatedStatus + '"]').prop('selected', true).prop('disabled', true);
                    }
                }
            })
        })
        $('body').on('click', '.prindbill', function (e) {
            e.preventDefault
            var id = $(this).attr('id');
            $.ajax({
                url: '/Admin/BuyBill/Generatepdf',
                type: 'GET',
                data: { idbill: id },
                success: function (response) {

                    location.href = "/Resource/Pdf/" + response;
                },
                error: function (error) {
                    console.log(error);
                }
            });
        })
    })
</script>

Website_clothe/Website_clothe/Areas/Admin/Views/BuyBill/Index.cshtml
@model IEnumerable<Website_clothe.Models.Donmuahang>
@{ 
    ViewBag.Title = "Quản lý đơn hàng";
}
<div class="container-fluid mt-4 px-4">
    <div class="card">
        <div class="card-header d-flex justify-content-between">
            <h3>Danh sách đơn hàng</h3>
        </div>
        <div class="card-body">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Mã đơn hàng</th>
                        <th>Tên người đặt hàng</th>
                        <th>Tổng đơn</th>
                        <th>Ngày tạo</th>
                        <th>Hành động</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.ID_Donhang</td>
                            <td>@item.Tennguoidung</td>
                            <td>@item.Tongdonhang đ</td>
                            <td>@item.Ngaytao.Value.ToString("dd/MM/yyyy")</td>
                            <td>
                                <a class="btn btn-danger" href="@Url.Action("DeleteBill", "BuyBill", new { id = item.ID_Donhang })">Xóa</a>
                                <a class="btn btn-info" href="@Url.Action("Detail", "BuyBill", new { id = item.ID_Donhang })">Chi tiết</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Website_clothe/Website_clothe/Areas/Admin/Views/BuyBill/PartialViewPdfResult.cshtml
@model Website_clothe.Models.billoforder

<style>
    /*.bigger_parent {
        display: flex;
        flex-direction: row;
        width: 100%;
        justify-content: center;
    }

    .child_parent {
        display: flex;
        flex-direction: column;
        padding: 0 10px 0;
        width: 80%;
        justify-content: center;
    }

    .child_1 {
        display: flex;
        flex-direction: row;
        justify-content: space-between;
    }

    .child_1_1, {
        width: 245px;
        height: max-content;
        display: flex;
        flex-direction: column;
    }

    .child_1_2_1, .child_1_2_2 {
        width: 245px;
        height: max-content;
        display: flex;
        flex-direction: row;
        margin: 0;
        padding: 0;
    }

        .child_1_2_1 p, .child_1_2_2 p {
            margin-right: 20px;
        }

    .child_1_1 p {
        margin-bottom: 20px;
    }

    .child_2 {
        width: 100%;
        display: flex;
        justify-content: center;
    }

    .child_3 {
        width: 100%;
        display: flex;
        flex-direction: row;
    }

    .child_3_sub {
        width: 250px;
        display: flex;
        flex-direction: column;
    }

    .sub_1, .sub_2 {
        display: flex;
        flex-direction: row;
        justify-content: space-evenly;
        width: 100%;
        height: max-content;
    }*/
    body {
        margin: 0;
        padding: 0;
        font-family: Arial, sans-serif;
    }

    /* General styles for the entire invoice container */
    .invoice-container {
        width: 100%;
        max-width: 800px; /* Adjust this width according to your preference */
        margin: 0 auto;
        padding: 20px;
        background-color: #fff;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    /* Header Section */
    .header-section {
        text-align: center;
        margin-bottom: 20px;
    }

    .store-info {
        font-weight: bold;
        margin-bottom: 10px;
    }

    .invoice-details {
        display: flex;
        justify-content: space-between;
    }

        .invoice-details p {
            margin: 5px 0;
        }

    .invoice-num,
    .invoice-date {
        text-align: left;
    }

    /* Customer & Delivery Info */
    .customer-info {
        display: flex;
        justify-content: space-between;
        margin-bottom: 20px;
    }

    .customer-details,
    .delivery-info {
        margin-bottom: 10px;
        width: 48%;
    }

        .delivery-info p {
            margin: 5px 0;
        }

    /* Table - Product List */
    .product-table {
        width: 100%;
        border-collapse: collapse;
        margin-bottom: 20px;
    }

        .product-table th,
        .product-table td {
            border: 1px solid #ddd;
            padding: 8px;
        }

        .product-table th {
            background-color: #f2f2f2;
        }

    /* Total Amount */
    .total-amount {
        text-align: right;
        margin-bottom: 20px;
    }

    /* Signatures */
    .signatures {
        display: flex;
        justify-content: space-between;
    }
</style>

@*<div class="bigger_parent">
    <div class="child_parent">
        <div class="child_1">
            <div class="child_1_1">
                <p>CỬA HÀNG FASHION</p>
                <p>Số 6, Phường 9, Quận 10, Tp. Hồ Chí Minh </p>
            </div>
            <div class="child_1_2">
                <div class="child_1_2_1">
                    <p>Số phiếu mua: </p>
                    <p>@Model.madonhang</p>
                </div>
                <div class="child_1_2_2">
                    <p>Ngày đặt: </p>
                    <p>@Model.ngaydat</p>
                </div>
            </div>
        </div>
        <div class="child_2">
            <h4>PHIẾU MUA HÀNG</h4>
        </div>
        <div class="child_3">
            <div class="child_3_sub">
                <div class="sub_1">
                    <div style="display:flex;flex-direction:row;width:300px;align-items:center">
                        <p style="margin-right:20px;width:min-content; display:block">Người lập phiếu:</p>
                        <p style="width: min-content;display:block">Admin</p>
                    </div>
                    <div style="display: flex; flex-direction: row; width: 300px">
                        <p style="margin-right: 20px; width: min-content;display:block">Số điện thoại người mua hàn:</p>
                        <p style="width: min-content;display:block">@Model.sodt</p>
                    </div>
                </div>
                <div class="sub_2">

                    <p>Địa chỉ giao hàng:</p>
                    <p>@Model.Diachi</p>

                </div>
            </div>
        </div>
        <div class="child_4">
            <table class="">
                <thead>
                    <tr class="">
                        <th>STT</th>
                        <th>Mã sản phẩm</th>
                        <th>Tên hàng</th>
                        <th>
                            Số lượng
                        </th>
                        <th>
                            Đơn giá
                        </th>
                        <th>
                            Thành tiền
                        </th>
                    </tr>
                </thead>
                <tbody class="text-center">
                    @foreach (var item in Model.ctdh)
                    {
                        int thanhtien = item.Soluongmua * item.Gia;
                        int i = 1;
                        <tr>
                            <td>@i</td>
                            <td>@item.mabienthe</td>
                            <td>@item.Tensanpham - @item.Size - @item.Mau</td>
                            <td>@item.Soluongmua</td>
                            <td>@String.Format("{0:#,##0}", item.Gia)</td>
                            <td>
                                @String.Format("{0:#,##0}", thanhtien)
                            </td>
                        </tr>
                        i++;
                    }
                </tbody>
            </table>
        </div>
        <div style="width:100%;display:flex;flex-direction:column;justify-content:left;margin-top:30px">
            <div style="display:flex;flex-direction:row">
                <div style="margin-right:20px"><p>Tổng đơn hàng mua:</p></div>
                <div><p>@String.Format("{0:#,##0}", Model.Tongdon) đồng</p></div>
            </div>
        </div>
        <div style="display:flex;flex-direction:row;justify-content:space-between">
            <div style="display:flex;flex-direction:column;align-items:center">
                <p style="margin:0">Người mua hàng</p>
                <p style="margin:0">(ký tên)</p>
            </div>
            <div style="display:flex;flex-direction:column;align-items:center">
                <p style="margin:0">Người lập phiếu</p>
                <p style="margin:0">(Ký tên)</p>
            </div>
        </div>
    </div>
</div>*@
<div class="invoice-container">
    <!-- Header Section -->
    <div class="header-section">
        <!-- Store Info -->
        <div class="store-info">
            <!-- Store Address -->
            <p>CỬA HÀNG FASHION</p>
            <p>Số 6, Phường 9, Quận 10, Tp. Hồ Chí Minh</p>
        </div>
        <!-- Invoice Details -->
        <div class="invoice-details">
            <div class="invoice-num">
                <p>Số phiếu mua:</p>
                <p>@Model.madonhang</p>
            </div>
            <div class="invoice-date">
                <p>Ngày đặt:</p>
                <p>@Model.ngaydat</p>
            </div>
        </div>
        <h4>PHIẾU MUA HÀNG</h4>
    </div>

    <!-- Customer & Delivery Info -->
    <div class="customer-info">
        <div class="customer-details">
            <p>Người lập phiếu: Admin</p>
            <p>Người nhận: @Model.Tennguoidung</p>
            <p>Số điện thoại người nhận: @Model.sodt</p>
        </div>
        <div class="delivery-info">
            <p>Địa chỉ giao hàng:</p>
            <p>@Model.Diachi</p>
        </div>
    </div>

    <!-- Table - Product List -->
    <table class="product-table">
        <!-- Table Header -->
        <thead>
            <!-- Table Headers: STT, Mã sản phẩm, Tên hàng, Số lượng, Đơn giá, Thành tiền -->
            <tr class="">
                <th>STT</th>
                <th>Mã sản phẩm</th>
                <th>Tên hàng</th>
                <th>
                    Số lượng
                </th>
                <th>
                    Đơn giá
                </th>
                <th>
                    Thành tiền
                </th>
            </tr>
        </thead>
        <!-- Table Body: Loop through items -->
        <tbody>
            <!-- Rows with product details -->
            @foreach (var item in Model.ctdh)
            {
                int thanhtien = item.Soluongmua * item.Gia;
                int i = 1;
                <tr>
                    <td>@i</td>
                    <td>@item.mabienthe</td>
                    <td>@item.Tensanpham - @item.Size - @item.Mau</td>
                    <td>@item.Soluongmua</td>
                    <td>@String.Format("{0:#,##0}", item.Gia)</td>
                    <td>
                        @String.Format("{0:#,##0}", thanhtien)
                    </td>
                </tr>
                i++;
            }
        </tbody>
    </table>

    <!-- Total Amount -->
    <div class="total-amount">
        <p>Tổng đơn hàng mua:</p>
        <p>@String.Format("{0:#,##0}", Model.Tongdon) đồng</p>
    </div>

    <!-- Signatures -->
    <div class="signatures">
        <!-- Người mua hàng, Người lập phiếu -->
        <div style="display:flex;flex-direction:column;align-items:center">
            <p style="margin:0">Người mua hàng</p>
            <p style="margin:0">(ký tên)</p>
        </div>
        <div style="display:flex;flex-direction:column;align-items:center">
            <p style="margin:0">Người lập phiếu</p>
            <p style="margin:0">(Ký tên)</p>
        </div>
    </div>
</div>